### ISSUE TITLE
After scroll. There's a living setInterval.

### ISSUE THREAD

**Issue by flaska** [Nolanus/ngx-page-scroll#232]
```
let pageScrollInstance: PageScrollInstance = PageScrollInstance.newInstance({
        document: this.document,
        scrollTarget: this.assembleId(ci, ti),
        pageScrollDuration: 500
      });
      this.pageScrollService.start(pageScrollInstance);
```

If you do this there will be a javascript interval which never disappears. Not a big deal unless you use protractor for testing and then you get this :( 
"Failed: Timed out waiting for asynchronous Angular tasks to finish after 11 seconds."

Proof:
Execute this script: 
```

window.originalSetTimeout=window.setTimeout;
window.originalClearTimeout=window.clearTimeout;
window.activeTimers=0;

window.setTimeout=function(func,delay)
{
    window.activeTimers++;
    return window.originalSetTimeout(func,delay);
};

window.clearTimeout=function(timerID)
{
    window.activeTimers--;
    window.originalClearTimeout(timerID);
};
```

Then u can easily check accessing: "window.activeTimers"

Thanks! Otherwise the lib is awesome!!!

**Comment by Nolanus** [comment]
Hi,

the timeouts you observe are related to and created by zoneJS. Note that `window.activeTimers` is > 0 even before triggering any scroll animation (it is 5 in the [demo app](https://nolanus.github.io/ng2-page-scroll/)). In addition to that you may put a `debugger;` statement into your monkey-patch method to inspect the stacktrace of the `setTimeout`.
Lastly, ng2-page-scroll uses `setInterval()` internally instead of `setTimeout()`.

**Comment by flaska** [comment]
thank you!
