### ISSUE TITLE
scrolling to top of container when anchor/target are within tables

### ISSUE THREAD

**Issue by skyleguy** [Nolanus/ngx-page-scroll#322]
I am demonstrating my issue in this stackblitz: https://stackblitz.com/edit/ngx-page-scroll-issue

I have some content in a small container. Both the anchor and the target are within tables. On click of the anchor id like to be scrolled to the target within the container. Because scrolling needs to happen in a container I am going the PageScrollService/Instance route. 

However when I click the anchor I am scrolled to the top of the container instead of to the target

I saw that there was another issue brought up about this but it was closed because the poster never responded. Any help would be great!

**Comment by Nolanus** [comment]
Hi. Thanks for creating a stackblitz showcasing the issue, it's much easier
to investigate than just by problem description and some code excerpts.
I'll take a look at it asap

Kyle <notifications@github.com> schrieb am Do., 23. Aug. 2018 17:16:

**Comment by skyleguy** [comment]
No problem! Hope it helps illuminate the issue. Would really like to keep using this package with my project!

**Comment by Nolanus** [comment]
Hi. I've taken a look at your example.

In order to determine the position of an element inside another scrollable container (other than the whole window), the element needs to be position relative to the parents. It does not help getting the position relative to the whole window if the scroll container is not the window.

Change the css `position` property of the scroll target to `relative` and the library can properly detect the position:
https://stackblitz.com/edit/ngx-page-scroll-issue-c8yghu?file=src/app/app.component.css

In case the "nested scrolling container" (`.container` in your example) is not positioned at the top left of the window, you also have to set the position of the container to `absolute` and the use `advancedInlineOffsetCalculation: true` setting for your pageScrollInstance. More details about that on the [wiki](https://github.com/Nolanus/ngx-page-scroll/wiki/FAQ#incorrect-scroll-position-with-nested-scrolling) and an example can be found at https://stackblitz.com/edit/ngx-page-scroll-issue-bxrbcm?file=src%2Fapp%2Fapp.component.ts

**Comment by skyleguy** [comment]
It seems as though just making the position relative is handling most of my issues, but the other advice may come in handy later. Thank you for the speedy responses!
