### ISSUE TITLE
PageScrollInstance: newInstance

### ISSUE THREAD

**Issue by taivu** [Nolanus/ngx-page-scroll#353]
I cant seem to find this method within the latest code. how do I use this method?

**Comment by Nolanus** [comment]
Since version 6 of ngx-page-scroll the method has been renamed to `create`:
https://github.com/Nolanus/ngx-page-scroll/blob/master/projects/ngx-page-scroll-core/src/lib/providers/ngx-page-scroll.service.ts#L70

To automatically create a PageScrollInstance and start the animation, you may use the `scroll` method:
https://github.com/Nolanus/ngx-page-scroll/blob/master/projects/ngx-page-scroll-core/src/lib/providers/ngx-page-scroll.service.ts#L225-L227

**Comment by taivu** [comment]
ahh thank you so much! upgraded from 4.0.beta9, so much has changed. Thank you for this library!
